#!/usr/bin/env python
import os

from ansible.module_utils.basic import *


def ensure_file_present(file):
    if os.path.isfile(file):
        return
    else:
        fp = open(file, 'w+')
        fp.close()
        return


def main():
    module = AnsibleModule(
        argument_spec=dict(
            file=dict(required=False, type='str', default="output.js"),
            var=dict(required=True, type='str'),
            value=dict(required=True),
        )
    )

    file = module.params.get('file')

    ensure_file_present(name)


main()